//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMKYRS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using static DMKYRS.Models.DataModels;

    public partial class ZadKyrsEntities : DbContext
    {
        public ZadKyrsEntities()
            : base("name=ZadKyrsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<StudentAnswer> StudentAnswer { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
