//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMKYRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAnswer
    {
        public int TaskID { get; set; }
        public string Login { get; set; }
        public string Answer { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Task Task { get; set; }
    }
}
