//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMKYRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string FamalyName { get; set; }
        public int SpecialityID { get; set; }
        public string Login { get; set; }
    
        public virtual Speciality Speciality { get; set; }
        public virtual Users Users { get; set; }
    }
}
